### ISSUE TITLE
Multiple canvases appear in viewer

### ISSUE THREAD

**Issue by nathanieldeines** [thegetty/dana#105]
Primary Issue: When viewing an image there are other canvases behind it. They stay there even when clicking to the next image. 

Steps to Recreate:
1. Navigate to http://dana.getty.edu/collections/2011m30/objects/2011m30_ref628_hdv
2. Click on "American Artists" tab.
3. Click on an item from the tab.
4. Observe the viewer.

Verified in Chrome, Safari, and Firefox.
![screen shot 2017-10-16 at 6 02 38 pm](https://user-images.githubusercontent.com/16109511/31641877-8ae03752-b29c-11e7-9bd7-6a875946d85e.png)

**Comment by joshuago78** [comment]
This has been determined to be a bug in Mirador, not DANA.
